language: node_js
node_js:
    - 14

install:
    - npm install -g gatsby-cli npm-check-updates
    - npm install

script:
    - node --experimental-json-modules src/scripts/calc.mjs
    - npm run build

deploy:
    provider: script
    script: npm install && npm run deploy
    skip_cleanup: true
    on:
      branch: master
